GRAILS-163 - Patch for cygwin problems
git-svn-id: https://svn.codehaus.org/grails/trunk@930 1cfb16fd-6d17-0410-8ff1-b7e8e1e2867d

diff --git a/bin/grails b/bin/grails
--- a/bin/grails
+++ b/bin/grails
@@ -1,15 +1,27 @@
 #!/bin/sh
 
+# OS specific support. $var must be set to either true or false.
+cygwin=false
+os400=false
+case "`uname`" in
+CYGWIN*) cygwin=true;;
+esac
+
+if $cygwin; then
+JAVA_HOME=`cygpath --windows "$JAVA_HOME"`
+GRAILS_HOME=`cygpath --windows "$GRAILS_HOME"`
+fi
+
 if [ -z "$JAVA_HOME" ] ; then
-  echo "Error: JAVA_HOME is not defined"
-  echo "Please set the JAVA_HOME environment variable and start Grails again"
-  exit 1
+echo "Error: JAVA_HOME is not defined"
+echo "Please set the JAVA_HOME environment variable and start Grails again"
+exit 1
 fi
 
 if [ -z "$GRAILS_HOME" ] ; then
-  echo "Error: GRAILS_HOME is not defined"
-  echo "Please define GRAIL_HOME and start Grails again"
-  exit 1
+echo "Error: GRAILS_HOME is not defined"
+echo "Please define GRAIL_HOME and start Grails again"
+exit 1
 fi
 
 ANT_HOME=${GRAILS_HOME}/ant
@@ -29,11 +41,14 @@ ANT_BIN=${ANT_HOME}/bin/ant
 BASEDIR=`pwd`
 
 case "`uname`" in
-  CYGWIN*)
-    GRAILS_BUILD_FILE=`cygpath --windows "$GRAILS_BUILD_FILE"`;
-    GRAILS_ANT_CLASSPATH=`cygpath --windows -p "$GRAILS_ANT_CLASSPATH"`
-    BASEDIR=`cygpath --windows "$BASEDIR"`
-    GRAILS_HOME=`cygpath --windows "$GRAILS_HOME"`
-   ;;
+CYGWIN*)
+GRAILS_BUILD_FILE=`cygpath --windows "$GRAILS_BUILD_FILE"`;
+GRAILS_ANT_CLASSPATH=`cygpath --windows -p "$GRAILS_ANT_CLASSPATH"`
+BASEDIR=`cygpath --windows "$BASEDIR"`
+GRAILS_HOME=`cygpath --windows "$GRAILS_HOME"`
+;;
 esac
-${ANT_BIN} --noconfig -lib "${GRAILS_ANT_CLASSPATH}" -f ${GRAILS_BUILD_FILE} -Dbasedir=${BASEDIR} -Dgrails.home=${GRAILS_HOME} $@
+
+${ANT_BIN} --noconfig -lib "${GRAILS_ANT_CLASSPATH}" -f
+${GRAILS_BUILD_FILE} -Dbasedir=${BASEDIR} -Dgrails.home=${GRAILS_HOME}
+$@
