Fix for OS X Leopard ulimit problem. GRAILS-1768
git-svn-id: https://svn.codehaus.org/grails/trunk@5837 1cfb16fd-6d17-0410-8ff1-b7e8e1e2867d

diff --git a/bin/startGrails b/bin/startGrails
--- a/bin/startGrails
+++ b/bin/startGrails
@@ -153,19 +153,21 @@ fi
 # Increase the maximum file descriptors if we can
 if [ "$cygwin" = "false" ]; then
     MAX_FD_LIMIT=`ulimit -H -n`
-    if [ $? -eq 0 ]; then
-        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-            # use the businessSystem max
-            MAX_FD="$MAX_FD_LIMIT"
-        fi
+	if [ "$MAX_FD_LIMIT" != "unlimited" ]; then
+	    if [ $? -eq 0 ]; then
+	        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+	            # use the businessSystem max
+	            MAX_FD="$MAX_FD_LIMIT"
+	        fi
         
-        ulimit -n $MAX_FD
-        if [ $? -ne 0 ]; then
-            warn "Could not set maximum file descriptor limit: $MAX_FD"
-        fi
-    else
-        warn "Could not query businessSystem maximum file descriptor limit: $MAX_FD_LIMIT"
-    fi
+	        ulimit -n $MAX_FD
+	        if [ $? -ne 0 ]; then
+	            warn "Could not set maximum file descriptor limit: $MAX_FD"
+	        fi
+	    else
+	        warn "Could not query businessSystem maximum file descriptor limit: $MAX_FD_LIMIT"
+	    fi
+	fi
 fi
 
 # Setup Profiler
